"""empty message

Revision ID: cd9f64a0d52e
Revises: 
Create Date: 2025-05-10 16:48:06.661470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9f64a0d52e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('height', sa.String(length=30), nullable=True),
    sa.Column('birth_year', sa.String(length=30), nullable=True),
    sa.Column('skin_color', sa.String(length=50), nullable=True),
    sa.Column('eyes_color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('climate', sa.String(length=80), nullable=True),
    sa.Column('population', sa.String(length=30), nullable=True),
    sa.Column('terrain', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('cost_credits', sa.String(length=30), nullable=True),
    sa.Column('max_speed', sa.String(length=30), nullable=True),
    sa.Column('crew', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usersFav_id', sa.Integer(), nullable=False),
    sa.Column('vehiclesFav_id', sa.Integer(), nullable=True),
    sa.Column('planetsFav_id', sa.Integer(), nullable=True),
    sa.Column('charactersFav_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charactersFav_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planetsFav_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['usersFav_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehiclesFav_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
